name: opencv_dart
description: "OpenCV4 bindings for Dart language and Flutter, using dart:ffi. The most complete OpenCV bindings for Dart!"
version: 1.0.0+2
binary_version: 1.0.0+2
homepage: https://github.com/rainyl/opencv_dart

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
  equatable: ^2.0.5
  yaml: ^3.1.2
  path: ^1.9.0
  args: ^2.4.2
  archive: ^3.4.10
  native_assets_builder: ^0.6.1
  native_assets_cli: ^0.5.4
  native_toolchain_c: ^0.4.1
  logging: ^1.2.0

dev_dependencies:
  ffigen: ^11.0.0
  flutter_lints: ^3.0.1
  test: ^1.25.2

topics:
  - opencv
  - image
  - ffi
  - flutter
