name: opencv_dart
description: |
  OpenCV4 bindings for Flutter, using dart:ffi.
  This plugin include `videoio` module, if you don't need it,
  please use `opencv_core` instead.
version: 1.3.3
opencv_version: 4.10.0+10
dartcv_version: 4.10.0.6
repository: https://github.com/rainyl/opencv_dart
homepage: https://github.com/rainyl/opencv_dart/tree/main/packages/opencv_dart

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartcv4: ^1.0.1

dev_dependencies:
  test: ^1.25.2

topics:
  - opencv
  - image
  - ffi
  - flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      ios:
        ffiPlugin: true
