name: opencv_dart
description: |
  OpenCV4 bindings for Flutter, using dart:ffi.
  This plugin include videoio module, if you doesn't need it,
  please use opencv_core instead.
  The most complete OpenCV bindings for Dart!
  With asynchronous support now!
version: 1.2.5
homepage: https://github.com/rainyl/opencv_dart

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartcv:
    path: ../dartcv

dev_dependencies:
  test: ^1.25.2

topics:
  - opencv
  - image
  - ffi
  - flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      ios:
        ffiPlugin: true
