name: dartcv
description: |
  OpenCV bindings for Dart language.
  dartcv is for pure dart only,
  for flutter, please use [opencv_core](https://pub.dev/packages/opencv_core),
  if you need videoio module, use [opencv_dart](https://pub.dev/packages/opencv_dart).
version: 0.0.1
homepage: https://github.com/rainyl/opencv_dart/packages/dartcv

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  ffi: ^2.1.3

dev_dependencies:
  ffigen: ">=13.0.0 <15.0.0"
  test: ^1.25.2

topics:
  - opencv
  - image
  - ffi
  - flutter
