name: android

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]

jobs:
  android:
    name: android
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86_64]
    env:
      COMMON_CMAKE_OPTIONS: |
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake \
        -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=False \
        -DANDROID_PLATFORM=android-24 \
        -DCMAKE_BUILD_TYPE=Release \
        -DANDROID_STL=c++_static \
        -DANDROID_ARM_NEON=ON \
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'https://github.com/rainyl/dartcv.git'
          ref: 'main'
      - name: build
        run: |
          mkdir build && cd build
          cmake -S ${{ github.workspace }} \
          ${{ env.COMMON_CMAKE_OPTIONS }} -DANDROID_ABI="${{ matrix.abi }}" \
            -DCMAKE_INSTALL_PREFIX="${{ matrix.abi }}" \

          cmake --build . --config Release -j $(nproc)
          cmake --build . --config Release --target install
      - uses: actions/upload-artifact@v4
        name: upload
        with:
          path: build/${{ matrix.abi }}
          name: libdartcv-android-${{ matrix.abi }}

  release:
    name: android
    runs-on: ubuntu-24.04
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          path: libdartcv-android
          pattern: libdartcv-android*
          merge-multiple: true
      - name: package
        run: |
          ls -R libdartcv-android
          tar -C libdartcv-android -zcvf libdartcv-android.tar.gz .
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: false
          files: |
            libdartcv-android.tar.gz
