name: build test

on:
  pull_request:
    branches: [ "main", "v0.6" ]

env:
  ANDROID_NDK_VERSION: r26c
  OPENCV_VERSION: 4.9.0
  LIB_NAME: libopencv_dart

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: build-opencv-dart
        run: |
          python3 -m pip install conan
          conan profile detect -f
          conan build . -b missing -s compiler.cppstd=20

      - uses: actions/upload-artifact@v4
        name: upload-windows-x64
        with:
          path: build/publish/libopencv_dart-windows-x64.tar.gz
          name: libopencv_dart-windows-x64.tar.gz
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: '3.16.9'
          channel: "stable"
      - name: Run Test
        run: |
          $env:PATH = "${{github.workspace}}\windows;${env:PATH}"
          flutter pub get
          flutter test -x no-local-files
