name: Examples

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/**"
      - "packages/opencv_dart/example/**"
      - "packages/opencv_core/example/**"
    paths-ignore:
      - "**.md"
      - "LICENSE"
  pull_request:

jobs:
  windows:
    name: windows
    runs-on: windows-2019
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: opencv_dart
        run: |
          cd packages/opencv_dart/example
          flutter build windows
      - name: opencv_core
        run: |
          cd packages/opencv_core/example
          flutter build windows
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git wget python3 unzip build-essential \
            libgtk-3-dev
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: opencv_dart
        run: |
          cd packages/opencv_dart/example
          flutter build linux
          flutter build apk --release --target-platform android-arm64,android-arm,android-x64 --split-per-abi
      - name: opencv_core
        run: |
          cd packages/opencv_core/example
          flutter build linux
          flutter build apk --release --target-platform android-arm64,android-arm,android-x64 --split-per-abi
  macos:
    name: macos
    runs-on: macos-13
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: opencv_dart
        run: |
          cd packages/opencv_dart/example
          flutter build macos
          flutter build ios --release --no-codesign
      - name: opencv_core
        run: |
          cd packages/opencv_core/example
          flutter build macos
          flutter build ios --release --no-codesign
  macos-arm:
    name: macos-arm
    runs-on: macos-14
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: opencv_dart
        run: |
          cd packages/opencv_dart/example
          flutter build macos
          flutter build ios --release --no-codesign
      - name: opencv_core
        run: |
          cd packages/opencv_core/example
          flutter build macos
          flutter build ios --release --no-codesign
