name: Examples

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"
  pull_request:
    branches: ["main"]

jobs:
  windows:
    name: windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: opencv_core
        run: |
          cd packages/opencv_core/example
          flutter build windows
      - name: opencv_dart
        run: |
          cd packages/opencv_dart/example
          flutter build windows
  android:
    name: android
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: opencv_core
        run: |
          cd packages/opencv_core/example
          flutter build apk --release --target-platform android-arm64,android-arm,android-x64 --split-per-abi
      - name: opencv_dart
        run: |
          cd packages/opencv_dart/example
          flutter build apk --release --target-platform android-arm64,android-arm,android-x64 --split-per-abi
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt-get install clang cmake git \
            ninja-build pkg-config \
            libgtk-3-dev liblzma-dev \
            libstdc++-12-dev
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: actions/checkout@v4
      - name: opencv_core
        run: |
          cd packages/opencv_core/example
          flutter build linux
      - name: opencv_dart
        run: |
          cd packages/opencv_dart/example
          flutter build linux
  macos:
    name: macos
    runs-on: macos-13
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: actions/checkout@v4
      - name: opencv_core
        run: |
          cd packages/opencv_core/example
          flutter build macos
      - name: opencv_dart
        run: |
          cd packages/opencv_dart/example
          flutter build macos
  macos-arm:
    name: macos-arm
    runs-on: macos-14
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: actions/checkout@v4
      - name: opencv_core
        run: |
          cd packages/opencv_core/example
          flutter build macos
      - name: opencv_dart
        run: |
          cd packages/opencv_dart/example
          flutter build macos
  ios:
    name: ios
    runs-on: macos-14
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: actions/checkout@v4
      - name: opencv_core
        run: |
          cd packages/opencv_core/example
          flutter build ios --release --no-codesign
      - name: opencv_dart
        run: |
          cd packages/opencv_dart/example
          flutter build ios --release --no-codesign
