name: Test

on:
  push:
    branches: ["main", "v0.6"]
  pull_request:
    branches: ["main", "v0.6"]

jobs:
  test-windows:
    name: test-windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: '3.16.9'
          channel: "stable"
      - name: Run Test
        run: |
          dart run opencv_dart:setup windows -a x64
          $env:PATH = "${{github.workspace}}\windows;${env:PATH}"
          flutter pub get
          flutter test -x no-local-files
